repos:
  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
      - id: check-toml
        name: Check Toml
        entry: check-toml
        language: system
        types: [toml]
      - id: check-yaml
        name: Check Yaml
        entry: check-yaml
        language: system
        types: [yaml]
      - id: end-of-file-fixer
        name: Fix End of Files
        entry: end-of-file-fixer
        language: system
        types: [text]
        stages: [pre-commit, pre-push, manual]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [pre-commit, pre-push, manual]
  # 引入 Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8 # 请使用最新的 Ruff 版本
    hooks:
      # 替代 flake8, isort, pyupgrade 等
      - id: ruff
        args: [--fix]
      # 替代 black
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
